version: 2

python:
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    # 위에 있는 requirements를 이용한 방법은 어째선지 빌드하기 전에 설치를 안 함
    install:
      - pip install -r requirements.txt
    build:
      html:
        - zensical build
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/
      - cp --recursive site/* $READTHEDOCS_OUTPUT/html/
